### ISSUE TITLE
Where has sleep() gone?

### ISSUE THREAD

**Issue by javafrog** [arduino-libraries/MKRWAN_v2#1]
In the previous version, there was a sleep method:

```
bool sleep(bool on = true) {
    sendAT(GF("+SLEEP="), on);
    if (waitResponse() != 1) {
      return false;
    }
    return true;
  }
```

which I could use to power down the modem. The method is missing now. How do I achieve the same?

**Comment by facchinm** [comment]
Hi @javafrog , sorry for the superlate response; sleep() was implemented for compatibility with Murata firmware, but in fact it was handled automatically by the module. This new version of the library gets rid of a bit of dust, so the function was removed (since it really wasn't needed)
