### ISSUE TITLE
1.3.1 firmware file

### ISSUE THREAD

**Issue by OriolFalip** [arduino-libraries/MKRWAN_v2#20]
Hi,

I updated my MKRWAN 1310 with the exemple code from the MKRWAN_v2 library:  MKRANFWUpdate_standalone and it gets updated to the Firmware version 1.3.0. 
Could you pls update the fw.h file to the one corresponding to the version 1.3.1? It has no sence that this library says it is for version 1.3.1 but updates it to 1.3.0.

If it is not updated in the repository, could anyone send me the fw.h for the 1.3.1?
Thank you

**Comment by per1234** [comment]
Hi @OriolFalip. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino-libraries/MKRWAN_v2/issues/4.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
