### ISSUE TITLE
Is SPI contention with the LORA module fixed in this library?

### ISSUE THREAD

**Issue by CanOfSocks** [arduino-libraries/MKRWAN_v2#23]
Hi,
I was wondering if the issues with SPI contention are still a problem for this library with the MKR WAN 1310, both for the external flash storage and other SPI devices.
I'd like to use the external flash and an SPI RFID reader, but would like to avoid resetting the lora module where possible.

Sorry if this topic isn't appropriate for this repo, but I believe you guys will give me the best answers.

Thanks

**Comment by aentinger** [comment]
Can you elaborate on what you mean by SPI contention? Arbitration on SPI is done via chip select lines dedicated for each slave. Consequently there can be no such thing as SPI "contention"-

**Comment by CanOfSocks** [comment]
Hi,
I'm referring to this issue from the [MKRWAN v1 library](https://github.com/arduino-libraries/MKRWAN/issues/76). I haven't been able to find if it has been fixed with my searches. I'm yet to test with my MKR WAN 1310 personally, but want to get an idea if I should expect to use workarounds with future projects.

**Comment by aentinger** [comment]
Hi,
Given that [MKRWAN_v2](https://github.com/arduino-libraries/MKRWAN_v2/blob/master/src/MKRWAN_v2.h) only uses `SerialLoRa` (which is the defined in [ArduinoCore-samd](https://github.com/arduino/ArduinoCore-samd/blob/master/variants/mkrwan1300/variant.h#L216)) and the fact `SerialLoRa` aka `Serial2` [is using the same SAMD pins](https://content.arduino.cc/assets/MKRWAN1310V3.0_sch.pdf) as the SPI connected to the SPI flash I have to say that YES, you still have to power down the modem if you want to talk to the flash :( .
