### ISSUE TITLE
MKR 1310 can't start LoRa Module 

### ISSUE THREAD

**Issue by fabioformiga** [arduino-libraries/MKRWAN_v2#3]
With the example LoRa Send and Receive the module MKR 1310 show the message "Failed to start module" (line 25 on the source example code). The module works fine on version first version of MKRWAN released on version 1.0.12.

**Comment by facchinm** [comment]
Hi @fabioformiga ,
this version of the library requires a different firmware (1.3.0) that you can flash using MKRWANFWUpdate_standalone sketch.
Let me know if it fixes the issue!
