### ISSUE TITLE
'SerialLoRa' was not declared in this scope when compiling for Portenta X8

### ISSUE THREAD

**Issue by marimelhanafy** [arduino-libraries/MKRWAN_v2#34]
When running (MKRWANFWUpdate_standalone.ino), I am getting this error:

```text
WARNING: library MKRWAN_v2 claims to run on samd, mbed architecture(s) and may be incompatible with your current board which runs on mbed_portenta architecture(s).
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino: In function 'void setup()':
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:39:18: error: 'SerialLoRa' was not declared in this scope
   port.dev   =  &SerialLoRa;
                  ^~~~~~~~~~
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:39:18: note: suggested alternative: 'SerialFifo'
   port.dev   =  &SerialLoRa;
                  ^~~~~~~~~~
                  SerialFifo
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:45:11: error: 'LORA_BOOT0' was not declared in this scope
   pinMode(LORA_BOOT0, OUTPUT);
           ^~~~~~~~~~
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:45:11: note: suggested alternative: 'LORA_OK'
   pinMode(LORA_BOOT0, OUTPUT);
           ^~~~~~~~~~
           LORA_OK
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:47:11: error: 'LORA_RESET' was not declared in this scope
   pinMode(LORA_RESET, OUTPUT);
           ^~~~~~~~~~
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:47:11: note: suggested alternative: 'LORA_ERROR'
   pinMode(LORA_RESET, OUTPUT);
           ^~~~~~~~~~
           LORA_ERROR
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino: In function 'void resetModuleRunning()':
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:270:16: error: 'LORA_BOOT0' was not declared in this scope
   digitalWrite(LORA_BOOT0, LOW);
                ^~~~~~~~~~
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:270:16: note: suggested alternative: 'LORA_OK'
   digitalWrite(LORA_BOOT0, LOW);
                ^~~~~~~~~~
                LORA_OK
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:271:3: error: 'SerialLoRa' was not declared in this scope
   SerialLoRa.end();
   ^~~~~~~~~~
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:271:3: note: suggested alternative: 'SerialFifo'
   SerialLoRa.end();
   ^~~~~~~~~~
   SerialFifo
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:274:16: error: 'LORA_RESET' was not declared in this scope
   digitalWrite(LORA_RESET, HIGH);
                ^~~~~~~~~~
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:274:16: note: suggested alternative: 'LORA_ERROR'
   digitalWrite(LORA_RESET, HIGH);
                ^~~~~~~~~~
                LORA_ERROR
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino: In function 'void loop()':
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:286:5: error: 'SerialLoRa' was not declared in this scope
     SerialLoRa.end();
     ^~~~~~~~~~
C:\Users\M\AppData\Local\Temp\.arduinoIDE-unsaved2023818-7392-ond0ck.taup\MKRWANFWUpdate_standalone\MKRWANFWUpdate_standalone.ino:286:5: note: suggested alternative: 'SerialFifo'
     SerialLoRa.end();
     ^~~~~~~~~~
     SerialFifo

exit status 1

Compilation error: 'SerialLoRa' was not declared in this scope
```

**Comment by cturvey** [comment]
This board? https://store-usa.arduino.cc/products/arduino-portenta-vision-shield-lora%C2%AE?selectedStore=us

This isn't really the MKR WAN 13xx series boards this code targets

You'd need to define SerialLoRa (Serial Instance), LORA_BOOT0 (GPIO Pin designation), LORA_RESET to platform appropriate values.

https://github.com/arduino-libraries/MKRWAN/blob/master/src/MKRWAN.h#L26

**Comment by marimelhanafy** [comment]
> This board? https://store-usa.arduino.cc/products/arduino-portenta-vision-shield-lora%C2%AE?selectedStore=us
> 
> This isn't really the MKR WAN 13xx series boards this code targets
> 
> You'd need to define SerialLoRa (Serial Instance), LORA_BOOT0 (GPIO Pin designation), LORA_RESET to platform appropriate values.
> 
> https://github.com/arduino-libraries/MKRWAN/blob/master/src/MKRWAN.h#L26

I have a testbed that consists of 4 ESP-WROOM-32 units, each connected to different kinds of sensors. I want to send the data from all of them to the Portenta X8 simultaneously. I have also connected the Portenta X8 with the Portenta Max Carrier, which is already has the LoRaWAN Module. I have already completed the ESPs part, as I connected all of them to the WiFi and sent the data using the TCP protocol. I used these headers (#include <WiFi.h> / #include <AsyncTCP.h> / #include <ESPAsyncWebSrv.h>).
My question is: how should I receive the data on the Portenta X8? I searched but did not find any related header for it. So, could you please let me know what the possible solutions are for this?
I followed this tutorial (https://docs.arduino.cc/tutorials/portenta-max-carrier/connecting-to-ttn) and I got the error that I posted.

**Comment by cturvey** [comment]
Seems odd you'd get the other errors if PORTENTA_CARRIER was defined.
And where do you define SerialLoRa ? Presumably to Serial1 if that's what it is attached too.

'''
#define SerialLoRa  Serial1
#define PORTENTA_CARRIER
#include <MKRWAN.h>
'''

**Comment by marimelhanafy** [comment]
@facchinm @per1234 @cturvey @dcuartielles @pillo79, I am in need of help here. Could you please assist me? The code is not working at all. Is there another header missing for Portenta X8?
Thanks in advance.

**Comment by marimelhanafy** [comment]
> Not a board I'm using, you'll need to debug/diagnose why the compiler isn't pulling in the definitions. The pins physically called out here https://github.com/arduino-libraries/MKRWAN/blob/master/src/MKRWAN.h#L26 for the PORTENTA_CARRIER build. So either it's not being passed to the compiler via the make or build process, or what it's defining isn't correct ,ie PD_5 Perhaps you can have the build generate the intermediate pre-processor output, and inspect that to understand why these things aren't defined suitably for your board. Double check you're using the source matching that in the repository. Perhaps you have someone on your team who can assist you more directly?

I am the only one working on this part in my team, but thank you so much for replying. I will check your three notes or comments (1. either it's not being passed to the compiler via the make or build process, or what it's defining isn't correct, i.e., PD_5. / 2. Perhaps you can have the build generate the intermediate pre-processor output, and inspect that to understand why these things aren't defined suitably for your board. / 3. Ensure that the source you're using matches the one in the repository.) and comment back. Thank you.

**Comment by facchinm** [comment]
Hi everyone, the Portenta X8 is quite a different beast compared to the microcontroller based ones; we don't have any ready made library to talk with the Lora module, so you'll need to follow some Linux-fu:

* ensure /dev/ttymxc3 is present (Max carrier should get automatically recognized and add the proper device tree overlay at boot)
* launch a docker container where we'll be able to install some utilities ```docker run -it --device /dev/ttymxc3:/dev/ttymxc3 --privileged debian:11-slim```
* you can now install an utility to talk with the serial port (eg. microcom) and interact with the module ( `microcom -p /dev/ttymxc3 -s 19200` )

@jcarolinares @manchoz do you happen to have any python example for the X8+Max+Lora combination?

**Comment by marimelhanafy** [comment]
> Hi everyone, the Portenta X8 is quite a different beast compared to the microcontroller based ones; we don't have any ready made library to talk with the Lora module, so you'll need to follow some Linux-fu:
> 
> * ensure /dev/ttymxc3 is present (Max carrier should get automatically recognized and add the proper device tree overlay at boot)
> * launch a docker container where we'll be able to install some utilities `docker run -it --device /dev/ttymxc3:/dev/ttymxc3 --privileged debian:11-slim`
> * you can now install an utility to talk with the serial port (eg. microcom) and interact with the module ( `microcom -p /dev/ttymxc3 -s 19200` )
> 
> @jcarolinares @manchoz do you happen to have any python example for the X8+Max+Lora combination?

Thank you so much for your response. I will try out the solution you suggested. Additionally, I wanted to inquire if there's an alternative solution that would allow me to receive data directly from the Wi-Fi using the TCP protocol. I attempted to do this by uploading the code from Arduino IDE, but I couldn't find any header files for the Portenta X8.

**Comment by manchoz** [comment]
Yes, please see https://github.com/arduino/portenta-containers/tree/release/lora-node-x8

**Comment by marimelhanafy** [comment]
> Yes, please see https://github.com/arduino/portenta-containers/tree/release/lora-node-x8

I tried to clone this repository but encountered an error message. Could you please assist me with this issue?
![Capture1](https://github.com/arduino-libraries/MKRWAN_v2/assets/111123637/695984fa-2f41-4067-9c16-3a9a6cadf621)

**Comment by marimelhanafy** [comment]
> @marimelhanafy is your connection working? Can you ping, resolve hosts, etc.
> 
> Please consider also cloning the repo on your PC and copying only the `lora-node-x8` folder on the X8 using the `adb push` command.
> 
> ```shell
> [PC]$ git clone https://github.com/arduino/portenta-containers.git
> [PC]$ adb push portenta-containers/lora-node-x8 /var/rootdirs/home/fio/
> [PC]$ adb shell
> [X8]$ cd lora-node-x8
> [X8]$ newgrp - docker
> [X8]$ docker build compile -t lora-node-x8 .
> [X8]$ sed -i 's#hub.foundries.io/${FACTORY}/##g' docker-compose.yml
> [X8]$ docker compose up
> ```

Thank you for providing the steps, but in ([X8]$ docker build compile -t lora-node-x8 .) , I got an error message. 
![image](https://github.com/arduino-libraries/MKRWAN_v2/assets/111123637/abe185ea-0710-40ce-8a99-273ecff6a3ff)

**Comment by manchoz** [comment]
@marimelhanafy, the commands that starts with `[X8]$` must be run on the X8 after connecting to it with `adb shell`.

Also, I made a typo, the correct build command is:

`[X8]$ docker build -t lora-node-x8 .`

**Comment by marimelhanafy** [comment]
> @marimelhanafy, the commands that starts with `[X8]$` must be run on the X8 after connecting to it with `adb shell`.
> 
> Also, I made a typo, the correct build command is:
> 
> `[X8]$ docker build -t lora-node-x8 .`

I double checked and I ran the commands on X8 after doing `adb shell`.
Also, I tried to make it run and it ran, but I encountered a different error.
![image](https://github.com/arduino-libraries/MKRWAN_v2/assets/111123637/5443e8b0-182b-483b-895e-ef4a9ae4dbc7)

**Comment by marimelhanafy** [comment]
> Is there any firewall on your network?

I think yes, there might be a firewall in the network as it is not my private network. I will check this issue further. Thank you so much for your assistance and time and my apologies for any inconvenience caused.

**Comment by marimelhanafy** [comment]
> ```shell
> sed -i 's#hub.foundries.io/${FACTORY}/##g' docker-compose.yml
> ```

I have now resolved the network issue. However, I am getting an error with the step `[X8]$ sed -i 's#hub.foundries.io/${FACTORY}/##g' docker-compose.yml`. Could you please assist?:
![image](https://github.com/arduino-libraries/MKRWAN_v2/assets/111123637/c22895f2-1999-44bd-bdf8-11df16901ab1)

**Comment by manchoz** [comment]
@marimelhanafy, you are launching the command from the wrong directory.
You can alternatively launch either of the following commands:

```sh
[X8]$ cd lora-node-x8
[X8]$ sed -i 's#hub.foundries.io/${FACTORY}/##g' docker-compose.yml
```

or

```sh
[X8]$ sed -i 's#hub.foundries.io/${FACTORY}/##g' lora-node-x8/docker-compose.yml
```

@marimelhanafy I think getting familiar with the Linux command line would be a good idea before proceeding further. Here are a couple of links that you might find helpful:

* [The Linux command line for beginners](https://ubuntu.com/tutorials/command-line-for-beginners#1-overview)
* [Getting Started with Linux](https://www.digitalocean.com/community/tutorial-series/getting-started-with-linux)

**Comment by marimelhanafy** [comment]
> @marimelhanafy, you are launching the command from the wrong directory. You can alternatively launch either of the following commands:
> 
> ```shell
> [X8]$ cd lora-node-x8
> [X8]$ sed -i 's#hub.foundries.io/${FACTORY}/##g' docker-compose.yml
> ```
> 
> or
> 
> ```shell
> [X8]$ sed -i 's#hub.foundries.io/${FACTORY}/##g' lora-node-x8/docker-compose.yml
> ```
> 
> @marimelhanafy I think getting familiar with the Linux command line would be a good idea before proceeding further. Here are a couple of links that you might find helpful:
> 
> * [The Linux command line for beginners](https://ubuntu.com/tutorials/command-line-for-beginners#1-overview)
> * [Getting Started with Linux](https://www.digitalocean.com/community/tutorial-series/getting-started-with-linux)

I am quite familiar with Linux and OS, but perhaps I wasn't focused and missed it, sorry for that, but thank you so much for your assistance; everything is working now. 
My question now related to the Portenta X8+Max Carrier+LoRa combination. I'm trying to follow this tutorial (https://docs.arduino.cc/tutorials/portenta-max-carrier/connecting-to-ttn), but I'm unsure how to link what we've done so far to the steps in this tutorial. Could you clarify at which step I should start?

**Comment by manchoz** [comment]
@marimelhanafy, the tutorial you are referring to is dedicated to the H7. Unfortunately, we don't have a tutorial for LoRa and X8 at this moment, but you will definitely be able to run LoRaWAN on the X8 following the custom container tutorial available at [Deploy a Custom Container with Portenta X8 Manager](https://docs.arduino.cc/tutorials/portenta-x8/custom-container) and using the container at [portenta-containers/lora-node-x8](https://github.com/arduino/portenta-containers/tree/release/lora-node-x8).

Since your issue is unrelated to a problem with the `MKRWAN_v2` library, please open a ticket at pro@arduino.cc for further support.

@facchinm, please close the issue.

**Comment by marimelhanafy** [comment]
@manchoz I apologize for reopening the issue. I have successfully obtained the Device EUI of the Portenta X8 using these steps, which I am happy to share for everyone's benefit:
```
# Open adb shell
> adb shell

# Run docker image in detached mode (runs in another process in the background)
> sudo docker compose up -d

# Get docker container id of loranode image
# This will display all container ids, copy the id of lora node container
> sudo docker ps

# Bash into the running container
> sudo docker exec -it {continer_id} sh

# now you are inside the lora server
# now run the lora node python script
> python lora-node.py deviceinfo
```
The results are as follows:
![image](https://github.com/arduino-libraries/MKRWAN_v2/assets/111123637/8f98e9a7-012f-4b2f-82a3-7e43a38be1e0)

The Device EUI is used in the  tutorial I previously mentioned (https://docs.arduino.cc/tutorials/portenta-max-carrier/connecting-to-ttn). Now, I'm at step 4 (Sending Data to an Application in TTN). However, I'm encountering the same main issue: the #include <MKRWAN.h> header is not compatible with Portenta X8. Could you advise on how I can modify it to work correctly with X8?

**Comment by per1234** [comment]
Hi @marimelhanafy. This library and the MKRWAN library do not support the Portenta X8; only the Portenta H7 so the error messages you encountered are expected.
